# Generated by Django 4.0.4 on 2022-05-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
