# Generated by Django 4.0.4 on 2022-05-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_price_product_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature_img',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
