# Generated by Django 4.0.4 on 2022-05-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_first_name_address_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
